[package]
name = "prime_factorisation"
version = "0.1.0"
authors = ["rugg2 <romain.guion@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
